name: Package CI

on:
  push:
    branches: [ "main", "develop", "feature/*" ]
    paths: ['src/complexoperations/**', 'test/complexoperations/**', '*/*.toml']
    tags: v*
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    
jobs:
  build:
    uses: ./.github/workflows/1_1-package-code-check.yml
    secrets: inherit

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f dev_requirements.txt ]; then pip install -r dev_requirements.txt; fi
      - name: Create Dist
        run: |
          python -m build
      - name: Check Tag Type
        id: tagtype
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+[ab][0-9]+$ ]]; then
              echo ::set-output name=type::pre
          fi
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo ::set-output name=type::release
          fi
      - name: Publish PreRelease
        if: steps.tagtype.outputs.type == 'pre'
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          generateReleaseNotes: true
          token: ${{ secrets.MY_TOKEN }}
          prerelease: true
      - name: Publish Release
        if: steps.tagtype.outputs.type == 'release'
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          generateReleaseNotes: true
          token: ${{ secrets.MY_TOKEN }}
          prerelease: false