name: Package Code Check

on:
  workflow_call:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f dev_requirements.txt ]; then pip install -r dev_requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 --filename=./src/complexoperations/*.py --count --statistics
        flake8 --filename=./src/complexoperations/*.py --count --statistics --exit-zero --max-complexity=10 --max-line-length=127
        flake8 --filename=./test/complexoperations/*.py --count --statistics
        flake8 --filename=./test/complexoperations/*.py --count --statistics --exit-zero --max-complexity=10 --max-line-length=127
    - name: Test with pytest
      run: |
        pytest test/complexoperations