# Publish Python Package to Pypi

name: PreRelease on PyPi

on:
  release:
    types: [prereleased]

jobs:
  
  publish:
    uses: ./.github/workflows/2_1-package-publish-on-pypi.yml
    with:
      tag_name: ${{ github.event.release.tag_name }}
    secrets: inherit
