name: Package to API CD

on:
  workflow_run:
    workflows: [Package Release]
    types: [completed]
    
jobs:
  
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/3_1-api-code-check.yml
    secrets: inherit

  deploy:
    needs: build
    uses: ./.github/workflows/3_2-api-deploy.yml
    with:
      tag_name: latest
    secrets: inherit
    
