name: FastAPI CI

on:
  push:
    branches: [ "main", "develop", "feature/*" ]
    paths: ['src/apicomplexoperations/**', 'test/apicomplexoperations/**']
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
   
  workflow_call:
   
    
jobs:
  
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f dev_requirements.txt ]; then pip install -r dev_requirements.txt; fi
        pip install -r src/apicomplexoperations/requirements.txt
    - name: Lint with flake8
      run: |
        flake8 --filename=./src/apicomplexoperations/*.py --count --statistics
        flake8 --filename=./src/apicomplexoperations/*.py --count --statistics --exit-zero --max-complexity=10 --max-line-length=127
        flake8 --filename=./test/apicomplexoperations/*.py --count --statistics
        flake8 --filename=./test/apicomplexoperations/*.py --count --statistics --exit-zero --max-complexity=10 --max-line-length=127
    - name: Test with pytest
      run: |
        pytest test/apicomplexoperations 

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/api-deploy.yml
    secrets: inherit
    
