name: FastAPI Deploy

on:
  workflow_call:
    inputs:
      heroku_app_name:
        required: true
        type: string
      heroku_email:
        required: true
        type: string
    secrets:
      HEROKU_API_KEY:
        required: true
  workflow_dispatch:
    inputs:
      heroku_app_name:
        required: true
        type: string
      heroku_email:
        required: true
        type: string
    secrets:
      HEROKU_API_KEY:
        required: true
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{ inputs.heroku_app_name }}
        heroku_email: ${{ inputs.heroku_email }}
        appdir: "src/apicomplexoperations"
