name: FastAPI Deploy

on:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
    secrets:
      HEROKU_API_KEY:
        required: true
      HEROKU_APP_NAME:
        required: true
      HEROKU_EMAIL:
        required: true
  workflow_dispatch:
    inputs:
      tag_name:
        required: true
        type: string
    secrets:
      HEROKU_API_KEY:
        required: true
      HEROKU_APP_NAME:
        required: true
      HEROKU_EMAIL:
        required: true
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check Tag Version
      id: tagver
      run: |
        if [[ ${{ inputs.tag_name }} =~ ^latest$ ]]; then
            echo ::set-output name=version::${{ inputs.tag_name }}
        else
            echo ::set-output name=version::tags/${{ inputs.tag_name }}
        fi
    - name: Fetch Github Release Asset
      uses: dsaltares/fetch-gh-release-asset@1.0.0
      with:
        regex: true
        file: "complexoperations.*"
        target: "src/apicomplexoperations/dep/"
        version: ${{ steps.tagver.outputs.version }}
        token: ${{ secrets.MY_TOKEN }}
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        appdir: "src/apicomplexoperations"
